/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // apiSidebar: [{type: 'autogenerated', dirName: './api'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-react/todo'],
  //   },
  // ],
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorial' // Generate sidebar slice from docs/tutorials/easy
    }
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api' // Generate sidebar slice from docs/api
    }
  ],
  exampleSidebar: [
    {
      type: 'autogenerated',
      dirName: 'examples' // Generate sidebar slice from docs/api
    }
  ]
};
